# Generated by Django 5.2 on 2025-05-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='feedimage',
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='feedimage1',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='feedimage2',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='feedimage3',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='feedimage4',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='feedimage5',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/'),
        ),
    ]
