# Generated by Django 5.2 on 2025-05-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0004_remove_gallery_feedimage_gallery_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('unisex', 'Unisex')], default='unisex', max_length=20),
        ),
    ]
